PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    isAdmin BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Movie (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    year INTEGER,
    createdById INTEGER NOT NULL,
    FOREIGN KEY (createdById) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Location (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT NOT NULL,
    streetAddress TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    createdById INTEGER NOT NULL,
    FOREIGN KEY (createdById) REFERENCES User(id),
    UNIQUE(description, streetAddress, city, country)
);

CREATE TABLE IF NOT EXISTS MovieLocation (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    movieId INTEGER NOT NULL,
    locationId INTEGER NOT NULL,
    addedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (movieId) REFERENCES Movie(id) ON DELETE CASCADE,
    FOREIGN KEY (locationId) REFERENCES Location(id) ON DELETE CASCADE,
    UNIQUE(movieId, locationId)
);
